--!optimize 2
--!nolint
--!nocheck
--!native
--# selene: allow(global_usage, multiple_statements, incorrect_standard_library_use, unused_variable)

-- Generated by roblox-llvm 0.0.0 beta
local lshift = _G.llvm_lshift or error("roblox-llvm | function 'lshift' not found (disable -cbit flag to use the default implementation)")
local rshift = _G.llvm_rshift or error("roblox-llvm | function 'rshift' not found (disable -cbit flag to use the default implementation)")
local arshift = _G.llvm_arshift or error("roblox-llvm | function 'arshift' not found (disable -cbit flag to use the default implementation)")
local band = _G.llvm_band or error("roblox-llvm | function 'band' not found (disable -cbit flag to use the default implementation)")
local bor = _G.llvm_bor or error("roblox-llvm | function 'bor' not found (disable -cbit flag to use the default implementation)")
local bxor = _G.llvm_bxor or error("roblox-llvm | function 'bxor' not found (disable -cbit flag to use the default implementation)")

local buffer = _G.llvm_buffer or error("roblox-llvm | function 'buffer' not found (disable -cbit flag to use the default implementation)")

local _hello = "Hello, World!\00"
function add(a, b)
    local result = a + b
    return result
end
function sub(a, b)
    local result = a - b
    return result
end
function mul(a, b)
    local result = a * b
    return result
end
function div(a, b)
    local result = a / b
    return result
end
function mod(a, b)
    local result = a % b
    return result
end
if not print then print = _G.llvm_print or error("roblox-llvm | function 'print' not found") end
function main()
    print()
    return 0
end
if script:IsA("BaseScript") then
    main()
end

return {add, sub, mul, div, mod, main, _hello}